### ISSUE TITLE
Improve dark-mode

### ISSUE THREAD

**Issue by DannyvdSluijs** [JsonMapper/jsonmapper.github.io#24]
The JsonMapper site has support for dark-mode and a very basic dark-mode was added.

This can be approved. JsonMapper uses [Tailwind](https://tailwindcss.com/) V3 which offers native support for [dark-mode](https://tailwindcss.com/docs/dark-mode#basic-usage).

**Comment by LucaScorpion** [comment]
Are there any specific bits you think need improvement? Cause from a quick comparison with the light mode I couldn't see anything that's "off", and overall it seems pretty decent already :)

**Comment by DannyvdSluijs** [comment]
I think mostly the logo in't showing that nice in dark-mode, compared to light mode.
<img width="316" alt="Screenshot 2023-03-21 at 20 59 52" src="https://user-images.githubusercontent.com/618940/226727189-5b1161f6-7d57-48d7-befa-647253a2c576.png">
<img width="302" alt="Screenshot 2023-03-21 at 21 01 00" src="https://user-images.githubusercontent.com/618940/226727256-28eed36e-8e38-43d2-a19f-e38a3d27b0a4.png">

I guess there is also some uncertainty I have as I would prefer the light-mode over the dark one. So I'm leaning to trust your opinion on this @LucaScorpion .

**Comment by DannyvdSluijs** [comment]
Closing for now as this was my point in improving the dark mode
